# config.py
import os
from datetime import datetime
# Configuration file for AI scripts and Telegram bot integration
# This file contains the necessary configurations and environment variables
# for the AI scripts to function correctly, including API keys, file paths, and other settings.

# You can find working production examples in the following github repositories:
# https://github.com/agigante80/OndaHertz_es website: https://www.ondahertz.es/
# https://github.com/agigante80/galena_es website: https://www.galena.es/

# The following variables must be set as environment variables for security reasons.
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
INDEXNOW_API_KEY = os.getenv("INDEXNOW_API_KEY")
#
# INDEXNOW_API_KEY is the variables for the IndexNow API
# This is your own IndexNow API key. You can get it at https://indexnow.org/
# If you don't want to use IndexNow, you can leave this variable empty.
#
# In Github, you can set them in the repository settings:
# - Go to your repository on GitHub.
# - Click on the "Settings" tab.
# - In the left sidebar, click on "Secrets and variables" and then "Actions".
# - Click the "New repository secret" button.
#

# Settting the variables for managing the topics
AI_TOPICS_DIRECTORY = "AI_content/"

# Settting the variables for the CSV files that will be used to manage the topics
CSV_FILE_LIST_OF_NEW_TOPICS = "list_of_NEW_topics.csv"
CSV_FILE_LIST_OF_ARCHIVED_TOPICS = "list_of_ARCHIVED_topics.csv"
CSV_FILE_LIST_OF_ARCHIVED_AFFILIATE_TOPICS = "list_of_ARCHIVED_AFFILITE_topics.csv"
CSV_FILE_LIST_OF_ERROR_TOPICS = "list_of_ERROR_topics.csv"

# Ensure the AI topics directory exists
FILE_PATH_NEW_TOPICS = os.path.join(AI_TOPICS_DIRECTORY, CSV_FILE_LIST_OF_NEW_TOPICS)
FILE_PATH_ARCHIVED_TOPICS = os.path.join(AI_TOPICS_DIRECTORY, CSV_FILE_LIST_OF_ARCHIVED_TOPICS)
FILE_PATH_ERROR_TOPICS = os.path.join(AI_TOPICS_DIRECTORY, CSV_FILE_LIST_OF_ERROR_TOPICS)
FILE_PATH_ARCHIVED_AFFILIATE_TOPICS = os.path.join(AI_TOPICS_DIRECTORY, CSV_FILE_LIST_OF_ARCHIVED_AFFILIATE_TOPICS)

# Settting the variables for the images generated by the AI
AI_IMAGES_DIRECTORY = "assets/images/"

# Settting the variables for the articles generated by the AI
AI_ARTICLES_DIRECTORY = "_posts/"

# Settting the variables for logs
LOG_FULL_PATH = ""

# Settting the variables for the website to use in each prompt
WEBSITE_URL = "https://www.galena.es/"
WEBSITE_TITLE = "Galena Minerals Blog"
WEBSITE_DESCRIPTION = "Explore the fascinating world of minerals, mining, and gemstones with in-depth articles, guides, and news tailored for geology enthusiasts, educators, and earth science lovers."
WEBSITE_KEYWORDS = "minerals, mining, gemstones, geology, earth science, mineralogy, mining industry, gemstones guide, geology education"
WEBSITE_AUDIENCE = "Geology enthusiasts, educators, students, and general readers interested in minerals, mining, and earth sciences"
WEBSITE_LANGUAGE = "English"  # Define the main website language for the content



# Settting the variables for the current date and time
CURRENT_DATE = datetime.now().strftime("%Y-%m-%d-%H%M")

# Settting the variables for the affiliate content
AFFILIATE_CONTENT_DIRECTORY = "affiliate_content/"  